import { Printers, Users } from "../types";

export const printers: Printers = [
  {
    id: 1,
    name: "Creality Ender 3",
    price: 199,
    brand: "Creality",
    stock: 10,
  },
  {
    id: 2,
    name: "Anycubic Mega-S",
    price: 369,
    brand: "Anycubic",
    stock: 5,
  },
  {
    id: 3,
    name: "Prusa i3 MK3S+",
    price: 999,
    brand: "Prusa",
    stock: 3,
  },
  {
    id: 4,
    name: "FlashForge Creator Pro",
    price: 899,
    brand: "FlashForge",
    stock: 7,
  },
  {
    id: 5,
    name: "Ultimaker S5",
    price: 5995,
    brand: "Ultimaker",
    stock: 2,
  },
  {
    id: 6,
    name: "LulzBot Mini 2",
    price: 1495,
    brand: "LulzBot",
    stock: 4,
  },
  {
    id: 7,
    name: "Formlabs Form 3",
    price: 3499,
    brand: "Formlabs",
    stock: 1,
  },
  {
    id: 8,
    name: "MakerBot Replicator+",
    price: 1999,
    brand: "MakerBot",
    stock: 6,
  },
  {
    id: 9,
    name: "Dremel Digilab 3D45",
    price: 1799,
    brand: "Dremel",
    stock: 8,
  },
  {
    id: 10,
    name: "Zortrax M200 Plus",
    price: 2190,
    brand: "Zortrax",
    stock: 9,
  },
];

export const users: Users = [
  {
    id: 1,
    username: "johnsmith",
    token: "abc123xyz456",
    email: "johnsmith@example.com",
    isLogged: true,
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    username: "janesmith",
    token: "def456hij789",
    email: "janesmith@example.com",
    isLogged: false,
    address: "456 Oak St, Anytown, USA",
  },
  {
    id: 3,
    username: "bobdylan",
    token: "klm123nop456",
    email: "bobdylan@example.com",
    isLogged: true,
    address: "789 Elm St, Anytown, USA",
  },
  {
    id: 4,
    username: "alicewonderland",
    token: "qrs789tuv012",
    email: "alice@example.com",
    isLogged: false,
    address: "111 Maple St, Anytown, USA",
  },
  {
    id: 5,
    username: "charliebrown",
    token: "wxy345zab678",
    email: "charliebrown@example.com",
    isLogged: true,
    address: "222 Pine St, Anytown, USA",
  },
];
